### ISSUE TITLE
Bug: student.rda cannot be loaded

### ISSUE THREAD

**Issue by kevinwang09** [gvdr/learningtower_masonry#2]
Commit 549dc4e853e7ee18ff533772e462e0675071cf65 updated the `student.rda` and I could not load this file into my R session (3.6.3). 

Upon further inspection, this file went from 31.3MB to 61.2MB. However, it is quite strange that has happened because the other files it depends on 2006, 2009, 2012'2 stu_qqq.rds only has a small change. 

I am planning to regenerate this file by re-editing the `Bind_Rows.Rmd`. If I am successful, then I will also merge the changes in `Code/Bind_Rows.Rmd` and `Code/Binding.Rmd`.

**Comment by njtierney** [comment]
Just a note that if you want to decrease file size then `readr::write_rds(thing, compress = "xz")` should give you the best compression
